[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = COM14
monitor_port = COM14
monitor_speed = 115200
upload_speed = 115200
upload_resetmethod = dtr-rts

; Fix serial monitor hardware flow control
monitor_rts = 0
monitor_dtr = 0

board_build.flash_size = 4MB
board_build.partitions = default.csv

lib_deps =
    dfrobot/DFRobot_BMI160 @ ^1.0.0
    mobizt/Firebase ESP32 Client @ ^4.4.14